baseURL: https://gophergo.dev/
languageCode: en-us
title: Gopher Go!
theme: PaperMod
params:
  assets:
    disableHLJS: true

    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    safari_pinned_tab:  "/safari-pinned-tab.svg"

  profileMode:
    enabled: true
    title: "Just Go for it!"
    subtitle: "Pick an area to explore"
    imageUrl: "/ashley-mcnamara/GoCommunity.png"
    imageTitle: "Go Community"
    buttons:
      - name: Basics
        url: "/basics"
      - name: Standard Library
        url: "/std"
      - name: Coding Questions
        url: "/code"
      - name: Projects
        url: "/projects"
      - name: Go command
        url: "/cmd"
